=== tzimer/private-transaction-families/transaction_generator/config/config_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "/config_schema.json",
  "title": "Config Schema",
  "description": "Sawtooth transaction processor generator configuration schema",
  "type": "object",
  "properties": {
    "family_name": {
      "description": "family name for the transaction processor",
      "type": "string"
    },
    "family_version": {
      "description": "version of the transaction processor, must be grater than 0",
      "type": "number",
      "minimum": 0,
      "exclusiveMinimum": true
    },
    "payload_encoding": {
      "description": "how transaction payload will be encoded, only cbor or json are valid",
      "type": "string",
      "enum": [
        "cbor",
        "json"
      ]
    },
    "signer_priv_key": {
      "description": "path to file containing the signer private key in hex format, if missing a random key will be generated",
      "type": "string"
    },
    "txn_payload": {
      "description": "array of transactions payload in json format, must have at least one, each item should match payload_schema",
      "type": "array",
      "minItems": 1,
      "items": {
        "oneOf": [
          {
            "$ref": "#definitions/payload"
          },
          {
            "$ref": "#definitions/acl_payload"
          },
          {
            "$ref": "#definitions/funny_bunny_user_handle"
          },
          {
            "$ref": "#definitions/funny_bunny_balance_handle"
          },
          {
            "$ref": "#definitions/funny_bunny_bunny_repository"
          },
          {
            "$ref": "#definitions/funny_bunny_couples"
          }
        ]
      },
      "uniqueItems": false
    }
  },
  "required": [
    "family_name",
    "family_version",
    "payload_encoding",
    "txn_payload"
  ],
  "definitions": {
    "payload": {
      "type": "object",
      "properties": {
        "Verb": {
          "description": "action to be taken, only accept 'set', 'inc' or 'dec'",
          "type": "string",
          "enum": [
            "set",
            "inc",
            "dec",
            "setUser"
          ]
        },
        "Value": {
          "description": "value for the key, must be grater than 0",
          "type": "number",
          "minimum": 0,
          "exclusiveMinimum": true
        },
        "Name": {
          "description": "key name",
          "type": "string"
        },
        "Timestamp": {
          "description": "TBD",
          "type": "string"
        },
        "UID": {
          "description": "TBD",
          "type": "string"
        }
      },
      "required": [
        "Verb",
        "Name",
        "Timestamp",
        "UID"
      ]
    },
    "funny_bunny_user_handle": {
      "type": "object",
      "properties": {
        "Action": {
          "description": "action to be taken",
          "type": "string",
          "enum": [
            "add_user",
            "remove_user"
          ]
        },
        "Timestamp": {
          "description": "public key for member, group id for group",
          "type": "string",
          "uniqueItems": true
        },
        "UID": {
          "description": "(optional) array of address prefix (not including first 6 characters of family name) to assign to members or groups, prefix of 62 zeroes is allready reserved",
          "type": "string",
          "uniqueItems": true
        },
        "Name": {
          "description": "(optional) group that this member should belong to, group name must be added first with add_group txn",
          "type": "string"
        },
        "Email": {
          "description": "(optional) group that this member should belong to, group name must be added first with add_group txn",
          "type": "string"
        },
        "PhotoURL": {
          "description": "(optional) group that this member should belong to, group name must be added first with add_group txn",
          "type": "string"
        }

      },
      "required": [
        "Action",
        "Timestamp",
        "UID",
        "Name"
      ]
    },
    "funny_bunny_balance_handle": {
      "type": "object",
      "properties": {
        "Action": {
          "description": "action to be taken",
          "type": "string",
          "enum": [
            "set_balance",
            "change_balance"
          ]
        },
        "Money": {
          "description": "public key for member, group id for group",
          "type": "integer",
          "uniqueItems": true
        },
        "Carrots": {
          "description": "(optional) array of address prefix (not including first 6 characters of family name) to assign to members or groups, prefix of 62 zeroes is allready reserved",
          "type": "integer",
          "uniqueItems": true
        },
        "UID": {
          "description": "(optional) group that this member should belong to, group name must be added first with add_group txn",
          "type": "string"
        }


      },

      "anyOf": [
        {
            
            "required": [
                "Action",
                "UID",
                "Carrots",
                "Money"
            ]
            
        },
        {
            "required": [
              "Action",
              "UID",
              "Carrots"
            ]
        },
        {
          "required": [
            "Action",
            "UID",
            "Money"
          ]
      }

    ]
      
    },

    "funny_bunny_bunny_repository": {
      "type": "object",
      "properties": {
        "Action": {
          "description": "action to be taken",
          "type": "string",
          "enum": [
            "add_bunny", 
            "change_bunny_state"
          ]
        },
        "Bunny": {
          "description": "public key for member, group id for group",
          "type": "string",
          "uniqueItems": true
        },
        "Generation": {
          "description": "(optional) array of address prefix (not including first 6 characters of family name) to assign to members or groups, prefix of 62 zeroes is allready reserved",
          "type": "integer",
          "uniqueItems": true
        },
        "UID": {
          "description": "(optional) group that this member should belong to, group name must be added first with add_group txn",
          "type": "string"
        }, 
        "IsNew": {
          "description": "(optional) group that this member should belong to, group name must be added first with add_group txn",
          "type": "boolean"
        }, 
        "State": {
          "description": "(optional) group that this member should belong to, group name must be added first with add_group txn",
          "type": "string"
        }


      },

      "anyOf": [
        {
            
          "required": [
            "Action",
            "UID",
            "Bunny",
            "Generation",
            "IsNew",
            "State"
        ]
            
        },
        {
          "required": [
            "Action",
            "UID",
            "Bunny",
            "State"
        ]
        }

    ]
             
    },

    "funny_bunny_couples": {
      "type": "object",
      "properties": {
        "Action": {
          "description": "action to be taken",
          "type": "string",
          "enum": [
            "add_couple", 
            "remove_couple"
          ]
        },
        "Bunny": {
          "description": "public key for member, group id for group",
          "type": "string",
          "uniqueItems": true
        },
        "SonGeneration": {
          "description": "(optional) array of address prefix (not including first 6 characters of family name) to assign to members or groups, prefix of 62 zeroes is allready reserved",
          "type": "integer"
        },
        "UID": {
          "description": "(optional) group that this member should belong to, group name must be added first with add_group txn",
          "type": "string"
        }, 
        "InLoveWith": {
          "description": "(optional) group that this member should belong to, group name must be added first with add_group txn",
          "type": "string"
        }, 
        "LoveTime": {
          "description": "(optional) group that this member should belong to, group name must be added first with add_group txn",
          "type": "integer"
        },
        "TimeStr": {
          "description": "(optional) group that this member should belong to, group name must be added first with add_group txn",
          "type": "string"
        },
        "Timestamp": {
          "description": "(optional) group that this member should belong to, group name must be added first with add_group txn",
          "type": "integer"
        }

      }
             
    },
    "acl_payload": {
      "type": "object",
      "properties": {
        "Type": {
          "description": "used to detect this type of transaction, must be private_ledger_administration",
          "type": "string",
          "enum": [
            "private_ledger_administration"
          ]
        },
        "Action": {
          "description": "action to be taken",
          "type": "string",
          "enum": [
            "add_member",
            "add_group",
            "remove_member",
            "remove_group",
            "add_access",
            "remove_access",
            "add_to_group",
            "remove_from_group",
            "change_member_key",
            "update_svn"
          ]
        },
        "Key": {
          "description": "public key for member, group id for group",
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        },
        "Address": {
          "description": "(optional) array of address prefix (not including first 6 characters of family name) to assign to members or groups, prefix of 62 zeroes is allready reserved",
          "type": "array",
          "minItems": 0,
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        },
        "Group": {
          "description": "(optional) group that this member should belong to, group name must be added first with add_group txn",
          "type": "string"
        },
        "new_svn": {
          "description": "(optional) new svn for update svn transaction",
          "type": "integer"
        }
      },
      "required": [
        "Type",
        "Action",
        "Key"
      ]
    }



  }
}

=== tzimer/private-transaction-families/Debug/txn_balance.json
{
  "family_name": "private_intkey",
  "family_version": 1.0,
  "payload_encoding": "json",
  "signer_priv_key": "admin_keys/client_private_key.hexstr",
  "txn_payload":[
    {"Action": "set_balance","UID": "bb563a4d49384b794f7a35656453656347354f6b4558666b6f704752793832", "Money":1127137, "Carrots":50 },
	{"Action": "change_balance","UID": "bb563a4d49384b794f7a35656453656347354f6b4558666b6f704752793832", "Money":4},
	{"Action": "change_balance","UID": "bb563a4d49384b794f7a35656453656347354f6b4558666b6f704752793832", "Money":-10},
	{"Action": "change_balance","UID": "bb563a4d49384b794f7a35656453656347354f6b4558666b6f704752793832", "Carrots":5},
	{"Action": "change_balance","UID": "bb563a4d49384b794f7a35656453656347354f6b4558666b6f704752793832", "Money": -1, "Carrots":5}
  ]
}

=== tzimer/private-transaction-families/Debug/txn_add_couple.json
{
  "family_name": "private_intkey",
  "family_version": 1.0,
  "payload_encoding": "json",
  "signer_priv_key": "admin_keys/client_private_key.hexstr",
  "txn_payload":[

	{"Action": "add_couple", "UID": "bb563a4d49384b794f7a35656453656347354f6b4558666b6f704752793832", "Bunny":"12345", "SonGeneration": 2, "InLoveWith": "54321", "LoveTime": 6, "TimeStr": "915", "Timestamp": 1550994332640},
	{"Action": "add_couple", "UID": "bb563a4d49384b794f7a35656453656347354f6b4558666b6f704752793832", "Bunny":"11111", "SonGeneration": 2, "InLoveWith": "55555", "LoveTime": 6, "TimeStr": "915", "Timestamp": 1550994332640}

  ]
}

=== tzimer/private-transaction-families/Debug/txn_add_user.json
{
  "family_name": "private_intkey",
  "family_version": 1.0,
  "payload_encoding": "json",
  "signer_priv_key": "admin_keys/client_private_key.hexstr",
  "txn_payload":[
    {"Action": "add_user", "Name": "Tamar", "Timestamp": "1550994332640", "UID": "bb563a4d49384b794f7a35656453656347354f6b4558666b6f704752793832", "Email": "t.z@intel.com", "Url":"http" }

  ]
}

=== tzimer/private-transaction-families/Debug/txn_add_bunny.json
{
  "family_name": "private_intkey",
  "family_version": 1.0,
  "payload_encoding": "json",
  "signer_priv_key": "admin_keys/client_private_key.hexstr",
  "txn_payload":[

	{"Action": "add_bunny", "UID": "bb563a4d49384b794f7a35656453656347354f6b4558666b6f704752793832", "Bunny":"12345", "Generation": 1, "IsNew": false, "State": "idle"},
	{"Action": "add_bunny", "UID": "bb563a4d49384b794f7a35656453656347354f6b4558666b6f704752793832", "Bunny":"12325", "Generation": 1, "IsNew": false, "State": "idle"},
	{"Action": "add_bunny", "UID": "bb563a4d49384b794f7a35656453656347354f6b4558666b6f704752793832", "Bunny":"54321", "Generation": 1, "IsNew": false, "State": "idle"},
	{"Action": "add_bunny", "UID": "bb563a4d49384b794f7a35656453656347354f6b4558666b6f704752793832", "Bunny":"11111", "Generation": 1, "IsNew": false, "State": "idle"},
	{"Action": "add_bunny", "UID": "bb563a4d49384b794f7a35656453656347354f6b4558666b6f704752793832", "Bunny":"55555", "Generation": 1, "IsNew": false, "State": "idle"},
	{"Action": "change_bunny_state", "UID": "bb563a4d49384b794f7a35656453656347354f6b4558666b6f704752793832", "Bunny":"12325", "State": "inLove"}
	

  ]
}
